### ISSUE TITLE
Flatpak - Known Issues

### ISSUE THREAD

**Issue by JerryCasiano** [FontManager/font-manager#272]
**It is strongly recommended that you use a normal installation** whenever possible, resorting to Flatpak packages only when a package is unavailable for your distribution and you are unable to build from source. A normal installation will always provide the best experience and integration.

The reality is that the goals of a packaging system such as Flatpak simply conflict with utilities such as Font Manager.

Below is a listing of issues reported when using the Flatpak package :

- [ ] Does not list available fonts correctly
- [ ] Missing widgets in interface
- [ ] Application crashes or fails to list any fonts when accessing Google Fonts - #268 
- [ ] Previews added to Compare mode are sized inconsistently - #246 
- [ ] System themes are not used - #211
- [ ] System / Desktop preferences do not work - #291 

Issues that are only reproducible using the Flatpak version will be closed and added to this list if confirmed. While these type of issues sometimes point to problems in the code, or result in improvements for everyone, a lack of time and interest coupled with a small install base makes these a very low priority. Also, debugging issues which only occur in the Flatpak version is definitely not my idea of fun.

Examples of things that do not work in the Flatpak version and almost certainly never will :

-  System / Desktop preferences
-  Archive support using File Roller
-  File manager extensions
-  GNOME Shell Search Provider

Pull requests are always welcome. 

If you would like to work on these issues, or any other aspect of the application, please open a new issue in order to track / discuss any changes required.
